# golangci-lint 配置文件
# Phantom Server v1.1

run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.21'

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - typecheck

linters-settings:
  govet:
    check-shadowing: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
